### PR TITLE
Updated hxjava-std.jar with stripped com.sun package

### LINKED ISSUE #30: com.sun package
I'm working on improving completion time for Haxe/Java and noticed that there's a lot of weird types showing up from the `com.sun` package. I think we're supposed to ignore that completely. I can do that at compiler-level, but ideally we just strip this from the .jar so it improves overall processing time.

cc @dmitryhryppa

### PR DESCRIPTION
**Pull request by dmitryhryppa**
Here is `hxjava-std.jar` without `com.sun`;
File size has been reduced to 7mb

Just wondering what if some external Java libraries depend on `com.sun` and they will not work properly with `-java-lib`?

There are some users who tried to access this package before, see: https://github.com/HaxeFoundation/hxjava/issues/21

Closes #30

### CODE REVIEW

**Comment by Simn** [comment]
That was quick!

I "think" you're not supposed to use that package in the Java world, but I'm not sure.

**Comment by Gama11** [comment]
"You're not supposed to" might be quite different from what libraries do in practice...

**Comment by Simn** [comment]
Maybe, but in that case it's fair to `-java-lib` something else in. Our default state should be "clean" in this regard, and providing completion for something like `com.sun.corba.se.impl.orbutil.closure.Constant` looks really ghetto.

I'll merge this and reopen #21 so this can be discussed further.

**Comment by Simn** [comment]
Uhm, something is wrong. After updating my vshaxe now hangs in "Building Cache...". What's weird is that I'm not seeing any errors from Haxe.

Now I'm worried that the `com.sun` package might be referenced from other types, in which case we would have to filter them too.

**Comment by Simn** [comment]
I had to revert this change because there are multiple internal references to the `com.sun` package and it's a huge mess to figure this out. I'll instead look into whitelisting packages for completion.

**Comment by dmitryhryppa** [comment]
Hm, it works fine for me with haxe rc3, vshaxe 2.13.7 and vscode 1.37.0 on my java projects.

**Pull request merged**
