### PR TITLE
Fix for compilation failure when classpath string gets to large.

### PR DESCRIPTION
**Pull request by davidbruce**
I first ran into this issue in Feb 2019 when I had a project that depended on 23 jars fail.  I've been using this for some time now without any issues.  
The old method stitched together an incredibly long string with either ; or : as a delimiter between jars.  The lib directory is always used, so using a wildcard instead should not cause any issues.

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Does it work for all OSes and older versions of Java compiler?

**Comment by davidbruce** [comment]
@RealyUniqueName I have used it with Jdk 8, 11, and 15.  What is the minimum version of java that needs to be supported?

**Comment by RealyUniqueName** [comment]
Does it work for Windows, OSX, Linux?

**Comment by davidbruce** [comment]
@RealyUniqueName 

I have re-tested my change with -jvm and -java on Haxe Nightly 4.2.0-rc.1+edb7321f2 with AdoptOpen JDK 8.0.272 and 11.0.8 hotspot on Ubuntu 18.04, Windows 10 19041, and OSX 10.15.7.  

Would you like me to test older versions of haxe?  I could also make a different branch and update the Travis CI with some tests beyond just compiling.

**Comment by RealyUniqueName** [comment]
I don't think that's necessary.
I was worried about different OSes because I don't know much about java and asterisk could be something specific to a shell.
Thank you for PR and testing.

**Pull request merged**
