### PR TITLE
Update hxjava-std.jar

### LINKED ISSUE #23: [Feature request] Update hxjava-std.jar
Current hxjava-std.jar is six years old and does not have a lot of classes.
I think classes can be taken from openjdk-8

### PR DESCRIPTION
**Pull request by dmitryhryppa**
closes #23 

Not sure why previous .jar file is so small. The new one is 64mb. 
If everything is ok please accept this PR.

### CODE REVIEW

**Comment by nadako** [comment]
Did you run haxe unit test suite with this one? :)

**Comment by nadako** [comment]
Anyway, I think it's fine to just upgrade the jar for now, but for the future: why not just look for the `rt.jar` in the `JAVA_HOME` directory instead of having this copy? What do you think @waneck?

**Comment by nadako** [comment]
> Did you run haxe unit test suite with this one? :)

nvm, I just did and it passes

**Comment by Simn** [comment]
I'm not sure if casually increasing the size of this library file by an order of magnitude was such a great call. Haxe seems to struggle quite a bit dealing with this 64 MB file. This is obviously something we should fix in Haxe, but we should also look into why the file size differs like that.

@waneck: Any insight? Did you strip something in library file originally?

**Comment by waneck** [comment]
I made a small program using a java-based library to strip all code from the jar, and just keep the definitions. I'll see if I can find something that does that, or rewrite that program

**Comment by nadako** [comment]
@waneck any luck?:)

**Pull request merged**
